name: Bump versions for extension only (promotes patch branch to stable release)


on:
    workflow_dispatch: 

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Extract branch name # needed because github.ref will contain sth like refs/heads/2.6.x, so pushing to that will fail
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout master
        run: git fetch && git checkout master
      - name: Setup Git
        run: |
          sh scripts/set_git_credentials.sh
      - name: Update extension version in scripts folder
        id: update
        run: node scripts/bump_extension_version.js ${{steps.extract_branch.outputs.branch}}
      - name: Commit and Push
        run: sh scripts/commit_and_push.sh "bump extension version in scripts to ${{ steps.update.outputs.next_extension_version }}." ""
      
      - name: Switch branch 
        id: setup_branch
        run: |
          sh scripts/setup_branch.sh "promote_patch-dev"
      - name: Update VSCode extension version
        run:  |
          node scripts/update_package_json_files.js dev ${{ steps.update.outputs.next_extension_version }} ""
      - name: Install Dependencies
        run: npm install
      - name: Commit and Push
        run: |
          sh scripts/commit_and_push.sh "bump extension version in package.json to ${{ steps.update.outputs.next_extension_version }}." ""
      
      - name: Trigger next workflow for LSP Unit tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Unit tests for LSP and publish
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{ "npm_channel": "latest", "extension_version": "${{ steps.update.outputs.next_extension_version }}", "branch": "stable" }'
