name: Publish 

on:
  workflow_dispatch:
    inputs:
      asset_name:
        description: 'Name of the .vsix file in the release'
        required: true
      tag_name: 
        description: 'The release version to fetch from.'
        required: true
      

jobs:
  marketplace:
    name: Publish to marketplace
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "carmenberndt/philodendron"
          version: "tags/${{ github.event.inputs.tag_name }}"
          file: ${{ github.event.inputs.asset_name }}
          token: ${{ secrets.GH_TOKEN }}
      - name: publish vsix to marketplace
        run: npm run deploy --pat ${{ secrets.PAT}} --packagePath ${{github.workspace}}/${{ github.event.inputs.asset_name }}
